version: '3.1'

services:
  mysql-container:
    image: mysql:8.0
    container_name: my-mysql-container
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: freshhuk
      MYSQL_DATABASE: my_db
      MYSQL_USER: freshhuk
      MYSQL_PASSWORD: freshhuk
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  my-hero-app:
    platform: linux/amd64
    build: .
    depends_on:
      - mysql-container
    environment:
      SPRING_APPLICATION_NAME: my-hero-app
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_DATABASE: my_db
      DB_USERNAME: freshhuk
      DB_PASSWORD: freshhuk

volumes:
  mysql-data:
